### ISSUE TITLE
[Feature request] Shape of the piemenu 

### ISSUE THREAD

**Issue by Grubuntu** [Grubuntu/PieMenu-Improved#14]
When a pieMenu has less than 6 to 8 elements, the buttons are far from each other.
Actually :
![Capture d’écran (33)](https://github.com/Grubuntu/PieMenu-Improved/assets/56045316/1ea148a8-72da-4fe6-895f-bb9b80f5093c)
![Capture d’écran (34)](https://github.com/Grubuntu/PieMenu-Improved/assets/56045316/2813484b-1a4f-4a1f-9f07-ee7d6e15426f)
![Capture d’écran (35)](https://github.com/Grubuntu/PieMenu-Improved/assets/56045316/658f9222-71ae-4f9f-980e-b112f1034b58)
![Capture d’écran (36)](https://github.com/Grubuntu/PieMenu-Improved/assets/56045316/e48554f8-b148-4a1a-9d21-4e2eecd852cb)
![Capture d’écran (37)](https://github.com/Grubuntu/PieMenu-Improved/assets/56045316/01d32485-4d6c-4d8a-bb82-4cc5553ecace)

I thought I modified the code a little to ensure that when there are less than 8 elements in the menu, they are positioned first at the top... in the shape of a rainbow. 

![Capture d’écran (39)](https://github.com/Grubuntu/PieMenu-Improved/assets/56045316/1f95abcc-5966-4da4-84a7-4a18522316d7)
![Capture d’écran (40)](https://github.com/Grubuntu/PieMenu-Improved/assets/56045316/38ae9852-3363-4e5f-b20b-9828a051ade6)
![Capture d’écran (41)](https://github.com/Grubuntu/PieMenu-Improved/assets/56045316/f110bcc9-b197-4dbe-b2b3-bcdf011251db)
![Capture d’écran (42)](https://github.com/Grubuntu/PieMenu-Improved/assets/56045316/c4703d37-a7b3-44c8-b343-5826608cbaeb)
![Capture d’écran (43)](https://github.com/Grubuntu/PieMenu-Improved/assets/56045316/11fa75a1-0a51-4305-93b6-8808606ebaa9)
![Capture d’écran (44)](https://github.com/Grubuntu/PieMenu-Improved/assets/56045316/1129eb65-2934-40e2-bec8-836409fb6233)
![Capture d’écran (45)](https://github.com/Grubuntu/PieMenu-Improved/assets/56045316/44fc209b-df06-4a99-b777-7e5c2072a981)

Do you think this is a good idea, or is this not a good design for use?

Actual code :
https://github.com/Grubuntu/PieMenu-Improved/blob/56a110cf3a77ed17c2eed5a9fb1e663d03f26295/InitGui.py#L821-L832

Proposed code change :

```
            if commandNumber == 1:
                angle = 0
                buttonSize = self.buttonSize
                #####Adjust PieMenus when there is less than 8 QtoolButtons  ######
                angleStart = 3 * math.pi / 2 - angle
            else:
                if commandNumber < 8:
                    angle = 2 * math.pi / 8
                else:
                    angle = 2 * math.pi / commandNumber
                    
                buttonRadius = math.sin(angle / 2) * self.radius
                buttonSize = math.trunc(2 * buttonRadius / math.sqrt(2))
            if commandNumber > 1:
                angleStart = 3 * math.pi / 2 - (angle*(commandNumber+1))/2
                ##### End Adjust PieMenus when there is less than 8 QtoolButtons######
            if buttonSize > self.buttonSize:
                buttonSize = self.buttonSize
            else:
                pass
```

**Comment by pgilfernandez** [comment]
> Do you think this is a good idea, or is this not a good design for use?

Yes, I like the idea as I know some users would prefer this behavior but I would like to propose you something bigger and more customizable: some users reported they would like pies to not open in a circular shape but as a stack of table of rows and columns.
That way, I would suggest to extend each pie with a new parameter that let users choose the "type of pie". That way we can add different ways of arranging the pie commands and users just choose them from a list.
Some ideas:

<img width="295" alt="Screenshot 2024-01-21 at 18 18 16" src="https://github.com/Grubuntu/PieMenu-Improved/assets/5942369/bd873572-876c-4fce-b428-d89565b44316">

<img width="264" alt="Screenshot 2024-01-21 at 18 18 26" src="https://github.com/Grubuntu/PieMenu-Improved/assets/5942369/3035863f-67af-4913-abf5-740a18b83d4c">

<img width="334" alt="Screenshot 2024-01-21 at 18 18 49" src="https://github.com/Grubuntu/PieMenu-Improved/assets/5942369/9b688e1c-084a-4794-bf3a-c1bb608b2010">

The same way you can imagine another set vertically.

What do you think?

**Comment by Grubuntu** [comment]
> 
> * circle (classic)
> * circle (top to bottom, the one you are proposing)
> * circle (bottom to top, why not?)
> * table top
> * table bottom
> * table top-bottom
> * table left
> * table right
> * table left-right
> * ... more?
> 
> What do you think?


These are very good ideas, as long as the user can choose, it's very good.

This will take a little time to complete and make some choices (in particular, for the maximum number of shortcuts to display). Great work to come.

**Comment by pgilfernandez** [comment]
Well, I think common sense will tell each user what maximum number of commands to add, but I guess it has to be around 12 on each side (in the case you use top-and-bottom or left-and-right)... BTW, I don't like using more than 8 commands in circle ones as it's the only way to truly remember their position.

What I'm unsure about, is if we should let users decide their number of rows and columns or just play with fixed ones we decide internally and see if it works or there are users that ask for further customization...

Related with your original suggestion, I would like to ask for another "simple" feature that makes this one a little bit more complicated, just because it adds a new dimension on how to arrange icons, but let me introduce it in a new "Feature request", [here it is](https://github.com/Grubuntu/PieMenu-Improved/issues/16).

**Comment by Grubuntu** [comment]
v1.3.5 : I have updated the code with some shapes.
We will be able to add others as the tests progress.
