### ISSUE TITLE
[Feature request] Search box for Tools commands

### ISSUE THREAD

**Issue by pgilfernandez** [Grubuntu/PieMenu-Improved#3]
Hi,

It would be so handy being able to filter the looooong commands list from "Tools" with a search box.

Thanks!!

**Comment by Grubuntu** [comment]
Yes, i think it seems feasible and would be very practical.

**Comment by Grubuntu** [comment]
I have merge the new version 1.3.1 : With search box 

(I thought it would have been much more complicated to do than that !)

![Searchbox](https://github.com/Grubuntu/PieMenu-Improved/assets/56045316/81796046-9377-4dcd-a59d-7759b41b0c44)

**Comment by pgilfernandez** [comment]
What about a final "simple" request?: how about adding an "x" icon to clean the filter?

Thanks!

**Comment by Grubuntu** [comment]
I have updated the code with an icon for clear search box but I'm not very satisfied about the icon.
![Capture d’écran (30)](https://github.com/Grubuntu/PieMenu-Improved/assets/56045316/3bc5b45f-8ad5-4e46-b12a-a2e29f6fd780)

**Comment by pgilfernandez** [comment]
Great!

Don't worry, tomorrow I design one that better fits =)
